# CI de Nível 02 - Execução Agendada

# nome da pipeline
name: 'N2 - Execução Agendada'
# gatilho agendado = schedule

on:
  schedule:
    - cron: '0 17 * * *'

#tarefas dentro da pipeline = jobs

jobs:
  #nome do job
  testes-unitarios:
    # maquina onde o job vai rodar
    runs-on: ubuntu-latest

    # passos do job
    steps:
      # clone do projeto
      - name: Clonando o projeto
        uses: actions/checkout@v4

      # instalação do node
      - name: Instalando Node
        uses: actions/setup-node@v4
        with:
          node-version: latest 

      - name: Instalando Dependencias
        run: npm install

      # Executando testes
      - name: Executando testes unitarios
        run: npm test
      
      # Publicando resultados dos testes
      - name: Test Reporter
        uses: dorny/test-reporter@v1
        if: ${{ always() }}
        with:
          name: Testes
          path: test-results.xml
          reporter: java-junit 

      # Salvando relatório 
      - name: Salvando relatorio de execucao
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: ./test-results.xml
          name: Relatório-Testes
