name: 'N3 - Execução por push'

on:
  push:
    branches:
      - main

jobs:
  testes-unitarios:
    runs-on: ubuntu-latest

    steps:
      - name: Clonando o projeto
        uses: actions/checkout@v4

      - name: Instalando Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalando Dependências
        run: npm install

      - name: Executando testes unitários
        run: npm test
      
      # Publicando resultados dos testes
      - name: Test Reporter
        uses: dorny/test-reporter@v1
        if: ${{ always() }}
        with:
          name: Testes
          path: test-results.xml
          reporter: java-junit
        
      # Salvando relatório 
      - name: Salvando relatorio de execucao
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: ./test-results.xml
          name: Relatório-Testes
